#  ssl配置部分
#server:
#  ssl:
#    key-store: classpath:myssl.jks
#    key-store-type: JKS
#    key-alias: alias
#    key-store-password: 4C7uC4Mm



mybatis:
  type-aliases-package: com.wx.wx_routine.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles:
    active: pro
